// <auto-generated />
using System;
using LukaszDrozdzLab7Homework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LukaszDrozdzLab7Homework.Migrations
{
    [DbContext(typeof(StarFleet))]
    [Migration("20190616223054_Final")]
    partial class Final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.Cruiser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasStarDrive");

                    b.Property<float>("Isp");

                    b.Property<int>("Lasers");

                    b.Property<int>("PlasmaGuns");

                    b.Property<float>("TWR");

                    b.Property<float>("Thrust");

                    b.Property<float>("Weight");

                    b.HasKey("ID");

                    b.ToTable("Cruisers");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.CruiserRepair", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("ShipID");

                    b.HasKey("ID");

                    b.HasIndex("ShipID");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DTO.GetBasicCruiserDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasStarDrive");

                    b.Property<int>("Lasers");

                    b.Property<int>("PlasmaGuns");

                    b.HasKey("ID");

                    b.ToTable("GetBasicCruiserDTO");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DTO.GetBasicDestroyerDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeamTrackers");

                    b.Property<int>("Lasers");

                    b.HasKey("ID");

                    b.ToTable("GetBasicDestroyerDTO");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DTO.GetFullCruiserDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasStarDrive");

                    b.Property<float>("Isp");

                    b.Property<int>("Lasers");

                    b.Property<int>("PlasmaGuns");

                    b.Property<float>("TWR");

                    b.Property<float>("Thrust");

                    b.Property<float>("Weight");

                    b.HasKey("ID");

                    b.ToTable("GetFullCruiserDTO");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DTO.GetFullDestroyerDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeamTrackers");

                    b.Property<float>("Isp");

                    b.Property<int>("Lasers");

                    b.Property<float>("TWR");

                    b.Property<float>("Thrust");

                    b.Property<float>("Weight");

                    b.HasKey("ID");

                    b.ToTable("GetFullDestroyerDTO");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DTO.GetRepairDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("ShipID");

                    b.HasKey("ID");

                    b.ToTable("GetRepairDTO");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.Destroyer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeamTrackers");

                    b.Property<float>("Isp");

                    b.Property<int>("Lasers");

                    b.Property<float>("TWR");

                    b.Property<float>("Thrust");

                    b.Property<float>("Weight");

                    b.HasKey("ID");

                    b.ToTable("Destroyers");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DestroyerRepair", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("ShipID");

                    b.HasKey("ID");

                    b.HasIndex("ShipID");

                    b.ToTable("DestroyerRepair");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.Mission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CruiserID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int?>("DestroyerID");

                    b.Property<int>("ShipID");

                    b.HasKey("ID");

                    b.HasIndex("CruiserID");

                    b.HasIndex("DestroyerID");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.CruiserRepair", b =>
                {
                    b.HasOne("LukaszDrozdzLab7Homework.Models.Cruiser", "Ship")
                        .WithMany("Repairs")
                        .HasForeignKey("ShipID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.DestroyerRepair", b =>
                {
                    b.HasOne("LukaszDrozdzLab7Homework.Models.Destroyer", "Ship")
                        .WithMany("Repairs")
                        .HasForeignKey("ShipID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LukaszDrozdzLab7Homework.Models.Mission", b =>
                {
                    b.HasOne("LukaszDrozdzLab7Homework.Models.Cruiser")
                        .WithMany("Missions")
                        .HasForeignKey("CruiserID");

                    b.HasOne("LukaszDrozdzLab7Homework.Models.Destroyer")
                        .WithMany("Missions")
                        .HasForeignKey("DestroyerID");
                });
#pragma warning restore 612, 618
        }
    }
}
